plugins {
    id("io.micronaut.application") version "4.6.1" apply false
    id("io.micronaut.aot") version "4.6.1" apply false
    id("com.gradleup.shadow") version "8.3.9" apply false
    id("com.google.protobuf") version "0.9.4" apply false
}

subprojects {
    repositories {
        mavenCentral()
    }

    group = 'huragan11'

    plugins.withId('java') {
        java {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
        dependencies {
            runtimeOnly("org.yaml:snakeyaml")
        }
    }
}

