#Mon Nov 17 09:18:47 UTC 2025
jpa:
  default:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: update
micronaut:
  server:
    port: 8081
  application:
    name: order-service
  metrics:
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
datasources:
  default:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/orders`}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
grpc:
  channels:
    inventory:
      address: "localhost:50052"
      plaintext: true
  server:
    port: 50051